#!/usr/bin/env python3
"""Generate src/sine_lut.c: one electrical cycle of Q15 sine.

Built offline because the SDK's float sinf returned wrong values near
multiples of pi/2 on the RP2350, which put reverse-polarity pulses in the
coil PWM at each peak and zero crossing.
"""
import math, pathlib, sys

BITS = 10
n = 1 << BITS
vals = [int(round(32767 * math.sin(2 * math.pi * i / n))) for i in range(n)]
rows = ['    ' + ', '.join(f'{v:6d}' for v in vals[i:i + 8]) + ',' for i in range(0, n, 8)]
out = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'sine_lut.c'
out.write_text(f'''// Generated by tools/gen_sine_lut.py. Do not edit.
#include "microstep.h"

#if MICROSTEP_LUT_BITS != {BITS}
#error "regenerate sine_lut.c for MICROSTEP_LUT_BITS"
#endif

const int16_t microstep_sine_lut[1 << MICROSTEP_LUT_BITS] = {{
''' + '\n'.join(rows) + '\n};\n')
print('wrote', out, file=sys.stderr)
